#!/usr/bin/env node
// Balance report: plays every party with random-but-sensible play (cautious) and with its scripted strategies, and writes
// docs/balance.md: how often each ending comes up, how often the opposition moves, and how the party's support fares.
// usage: node tools/balance_report.js [games per row, default 100]   (run `npx dendrynexus make-html` first)
var cp = require('child_process');
var fs = require('fs');
var path = require('path');
var N = parseInt(process.argv[2] || '100', 10);
var ROOT = path.join(__dirname, '..');
var ROWS = [
  ['Mensheviks', 'Easy', 'cautious'], ['Mensheviks', 'Normal', 'cautious'], ['Mensheviks', 'Hard', 'cautious'],
  ['Mensheviks', 'Normal', 'bot:democrat'], ['Mensheviks', 'Normal', 'bot:vikzhelist'], ['Mensheviks', 'Normal', 'bot:opposition'], ['Mensheviks', 'Normal', 'bot:whiteaid'],
  ['Socialist Revolutionaries', 'Easy', 'cautious'], ['Socialist Revolutionaries', 'Normal', 'cautious'], ['Socialist Revolutionaries', 'Hard', 'cautious'],
  ['Socialist Revolutionaries', 'Normal', 'bot:sr_land'], ['Socialist Revolutionaries', 'Normal', 'bot:sr_komuch'], ['Socialist Revolutionaries', 'Normal', 'bot:sr_peasant'],
  ['Socialist Revolutionaries', 'Normal', 'bot:socializer'], ['Socialist Revolutionaries', 'Normal', 'bot:breaker'],
  ['Left SRs', 'Easy', 'cautious'], ['Left SRs', 'Normal', 'cautious'], ['Left SRs', 'Hard', 'cautious'], ['Left SRs', 'Normal', 'bot:lsr_coalition'], ['Left SRs', 'Normal', 'bot:lsr_rising'], ['Left SRs', 'Normal', 'bot:lsr_villages']
];
var LOSSES = {kornilov: 1, right_coup: 1, white: 1};
var HISTORICAL = {exile: 1, one_party: 1, sr_historical: 1, lsr_historical: 1};
var tmp = path.join(require('os').tmpdir(), 'ro_balance_' + process.pid + '.json');
var lines = ['# Balance report', '', 'Generated by `node tools/balance_report.js ' + N + '` (' + N + ' games a row). "cautious" picks a random sensible option every time; the `bot:` rows follow the scripted strategies in `tools/bots.js`.', '',
  '| Party | Difficulty | Play | Endings (%) | Won (%) | Historical (%) | Crushed (%) | Opposition moves a game | Peak support | Final support |', '|---|---|---|---|---|---|---|---|---|---|'];
ROWS.forEach(function(row) {
  var env = Object.assign({}, process.env, {PARTY: row[0], DIFF: row[1], JSON: tmp});
  cp.execFileSync('node', [path.join(__dirname, 'playtest.js'), String(N), row[2]], {cwd: ROOT, env: env, stdio: 'ignore'});
  var res = JSON.parse(fs.readFileSync(tmp, 'utf8')), counts = {}, lost = 0, hist = 0, opp = 0, peak = 0, fin = 0;
  res.forEach(function(r) {
    counts[r.ending] = (counts[r.ending] || 0) + 1;
    if (LOSSES[r.ending]) { lost++; }
    if (HISTORICAL[r.ending]) { hist++; }
    opp += r.opp[0] + r.opp[1] + r.opp[2]; peak += r.peak; fin += r.final_poll;
  });
  var endings = Object.keys(counts).sort(function(a, b) { return counts[b] - counts[a]; })
    .map(function(k) { return k + ' ' + Math.round(100 * counts[k] / res.length); }).join(', ');
  var n = res.length;
  lines.push('| ' + row[0] + ' | ' + row[1] + ' | ' + row[2] + ' | ' + endings + ' | ' + Math.round(100 * (n - lost - hist) / n) + ' | ' + Math.round(100 * hist / n) + ' | ' + Math.round(100 * lost / n) + ' | ' + (opp / n).toFixed(1) + ' | ' + Math.round(peak / n) + '% | ' + Math.round(fin / n) + '% |');
  process.stdout.write('.');
});
try { fs.unlinkSync(tmp); } catch (e) { /* already gone */ }
lines.push('', '"Crushed" is the party destroyed by force (Kornilov, the generals, the Whites). "Historical" is the party dissolved or driven abroad as in our world: exile, the one-party state, and the SR and Left SR historical endings. "Won" is the Constituent Republic, the all-socialist government, Soviet democracy, the Soviet coalition and the peasant soviets.');
fs.mkdirSync(path.join(ROOT, 'docs'), {recursive: true});
fs.writeFileSync(path.join(ROOT, 'docs', 'balance.md'), lines.join('\n') + '\n');
console.log('\nwrote docs/balance.md');
