#!/usr/bin/env node
// Fuzz run: plays many small batches of games, each with random settings (party, difficulty, play style, a bot's
// strategy and how often it strays from it), and writes docs/fuzz_report.md plus the raw data as JSON.
// usage: node tools/fuzz.js [batches, default 60] [games per batch, default 5] [seed, default the time]
// Every game has a seed: replay one with   SEED=<seed> PARTY=... DIFF=... NOISE=... node tools/playtest.js 1 <policy>
// (run `npx dendrynexus make-html` first)
var cp = require('child_process');
var fs = require('fs');
var os = require('os');
var path = require('path');
var ROOT = path.join(__dirname, '..');
var BATCHES = parseInt(process.argv[2] || '60', 10);
var PER = parseInt(process.argv[3] || '5', 10);
var SEED0 = parseInt(process.argv[4] || String(Date.now() % 1000000), 10);

var PARTIES = {Mensheviks: 'men', 'Socialist Revolutionaries': 'sr', 'Left SRs': 'lsr'};
var BOTS = {men: ['democrat', 'vikzhelist', 'opposition', 'whiteaid', 'persuader'],
            sr: ['sr_land', 'sr_komuch', 'sr_peasant', 'socializer', 'breaker'], lsr: ['lsr_coalition', 'lsr_rising', 'lsr_villages']};
var ALLBOTS = [].concat(BOTS.men, BOTS.sr, BOTS.lsr);
// crushed: the party is destroyed by force; historical: the party is dissolved or driven abroad, as it was in our world
var LOSSES = {kornilov: 1, right_coup: 1, white: 1};
var HISTORICAL = {exile: 1, one_party: 1, sr_historical: 1, lsr_historical: 1};

var s = SEED0;
function rand() { s = (s * 1103515245 + 12345) % 2147483648; return s / 2147483648; }
function pick(a) { return a[Math.floor(rand() * a.length)]; }

function config(i) {
  var party = pick(Object.keys(PARTIES)), diff = pick(['Easy', 'Normal', 'Normal', 'Hard']), r = rand(), policy, noise = 0;
  if (r < 0.15) { policy = 'random'; }
  else if (r < 0.25) { policy = 'first'; }
  else if (r < 0.45) { policy = 'cautious'; }
  else if (r < 0.9) { policy = 'bot:' + pick(BOTS[PARTIES[party]]); noise = pick([0, 0.1, 0.25, 0.5]); }
  else { policy = 'bot:' + pick(ALLBOTS); noise = pick([0, 0.25]); }   // a strategy written for another party
  return {batch: i, party: party, diff: diff, policy: policy, noise: noise, seed: SEED0 * 1000 + i * PER};
}

var tmp = path.join(os.tmpdir(), 'ro_fuzz_' + process.pid + '.json');
var games = [], crashes = [], failures = [];
var t0 = Date.now();
for (var b = 0; b < BATCHES; b++) {
  var c = config(b);
  var env = Object.assign({}, process.env, {PARTY: c.party, DIFF: c.diff, NOISE: String(c.noise), SEED: String(c.seed), JSON: tmp, STRICT: ''});
  var out = '';
  try {
    out = cp.execFileSync('node', [path.join(__dirname, 'playtest.js'), String(PER), c.policy], {cwd: ROOT, env: env, stdio: ['ignore', 'pipe', 'ignore'], maxBuffer: 64 << 20}).toString();
  } catch (e) {
    crashes.push({config: c, output: String(e.stdout || e.message).slice(-2000)});
    process.stdout.write('X');
    continue;
  }
  out.split('\n').forEach(function(line) {
    if (/^ERROR in run|^TEXT LEAKS|^  |^AMBIGUOUS|^STUCK/.test(line)) { failures.push({config: c, line: line.slice(0, 400)}); }
  });
  JSON.parse(fs.readFileSync(tmp, 'utf8')).forEach(function(g) { g.config = c; games.push(g); });
  process.stdout.write('.');
}
try { fs.unlinkSync(tmp); } catch (e) { /* gone */ }
console.log('\n' + games.length + ' games in ' + Math.round((Date.now() - t0) / 1000) + 's');

// ---------- the report ----------
function pct(n, d) { return d ? Math.round(100 * n / d) : 0; }
function tally(list, f) { var o = {}; list.forEach(function(x) { var k = f(x); o[k] = (o[k] || 0) + 1; }); return o; }
function fmt(o, n) { return Object.keys(o).sort(function(a, b) { return o[b] - o[a]; }).map(function(k) { return k + ' ' + pct(o[k], n); }).join(', '); }
function mean(list, f) { return list.length ? list.reduce(function(a, x) { return a + f(x); }, 0) / list.length : 0; }
function row(cells) { return '| ' + cells.join(' | ') + ' |'; }

var L = ['# Fuzz report', '',
  'Generated by `node tools/fuzz.js ' + BATCHES + ' ' + PER + ' ' + SEED0 + '`: ' + BATCHES + ' batches of ' + PER + ' games, each batch with random settings (party, difficulty, play style, and for the scripted bots a chance of straying to a random option). ' +
  games.length + ' games finished their run; percentages are of the games in that row. "Crushed" is Kornilov, the generals\' coup or the Whites; "Historical" is the party dissolved or driven abroad as in our world (exile, the one-party state, the SR and Left SR historical endings); "Won" is everything else.', ''];

L.push('## Problems', '');
var stuck = games.filter(function(g) { return g.ending === 'STUCK'; });
L.push('- Crashed batches: ' + crashes.length, '- Engine errors, text leaks, ambiguous go-to: ' + failures.filter(function(f) { return /^ERROR|^TEXT|^AMBIG/.test(f.line); }).length,
  '- Games that never ended: ' + stuck.length, '');
failures.forEach(function(f) { L.push('  - `' + f.config.party + ' / ' + f.config.diff + ' / ' + f.config.policy + ' noise ' + f.config.noise + '`: ' + f.line.replace(/\|/g, '/')); });
stuck.slice(0, 10).forEach(function(g) { L.push('  - stuck: seed ' + g.seed + ', ' + g.config.party + ' ' + g.config.policy + ', ' + g.month + '/' + g.year + ' after ' + g.steps + ' steps, last scenes ' + (g.last || []).join(' > ')); });
crashes.forEach(function(c) { L.push('  - crash: `' + JSON.stringify(c.config) + '`: ' + c.output.split('\n').slice(-3).join(' / ')); });
L.push('');

function table(title, key) {
  L.push('## ' + title, '', row(['Group', 'Games', 'Endings (%)', 'Won (%)', 'Historical (%)', 'Crushed (%)', 'Ends before Dec 1921 (%)', 'Peak support', 'Final support', 'Laws', 'Opposition moves']), row(['---', '---', '---', '---', '---', '---', '---', '---', '---', '---', '---']));
  var groups = {};
  games.forEach(function(g) { var k = key(g); (groups[k] = groups[k] || []).push(g); });
  Object.keys(groups).sort().forEach(function(k) {
    var gs = groups[k], n = gs.length;
    L.push(row([k, n, fmt(tally(gs, function(g) { return g.ending; }), n),
      pct(gs.filter(function(g) { return !LOSSES[g.ending] && !HISTORICAL[g.ending] && g.ending !== 'STUCK'; }).length, n),
      pct(gs.filter(function(g) { return HISTORICAL[g.ending]; }).length, n), pct(gs.filter(function(g) { return LOSSES[g.ending]; }).length, n),
      pct(gs.filter(function(g) { return g.year < 1921 || (g.year === 1921 && g.month < 12); }).length, n),
      Math.round(mean(gs, function(g) { return g.peak; })) + '%', Math.round(mean(gs, function(g) { return g.final_poll; })) + '%',
      mean(gs, function(g) { return g.laws; }).toFixed(1), mean(gs, function(g) { return g.opp[0] + g.opp[1] + g.opp[2]; }).toFixed(1)]));
  });
  L.push('');
}
table('By party', function(g) { return g.config.party; });
table('By party and difficulty', function(g) { return g.config.party + ', ' + g.config.diff; });
table('By play style', function(g) { return g.config.party + ', ' + (g.config.policy.indexOf('bot:') === 0 ? 'bot' + (g.config.noise ? ' +' + g.config.noise + ' noise' : '') : g.config.policy); });
table('By scripted strategy', function(g) { return g.config.policy.indexOf('bot:') === 0 ? g.config.party + ', ' + g.config.policy.slice(4) : '(not a bot)'; });

// when the games end
L.push('## When the games end', '', row(['Year', 'Games (%)']), row(['---', '---']));
var byYear = tally(games, function(g) { return g.year; });
Object.keys(byYear).sort().forEach(function(y) { L.push(row([y, pct(byYear[y], games.length)])); });
L.push('');

// the numbers: where they sit, and how often they hit the walls
L.push('## The numbers over a game', '', 'For each game, its lowest and highest value (sampled every turn) and its value at the end; the table gives the averages, and the share of games that touched 5 or less, or 95 or more, at some point.', '',
  row(['Number', 'Mean low', 'Mean high', 'Mean at the end', 'Games down to 5 or less', 'Games up to 95 or more']), row(['---', '---', '---', '---', '---', '---']));
['bread', 'ruble', 'player_poll', 'soviet_democracy', 'war_weariness', 'right_threat', 'bolshevik', 'ant_kad', 'ant_gen', 'ant_bol', 'repression', 'white_front', 'resources'].forEach(function(k) {
  var gs = games.filter(function(g) { return g.lo && g.lo[k] !== undefined; });
  if (!gs.length) { return; }
  var startsLow = /^ant_|repression|white_front|resources/.test(k);
  L.push(row([k, Math.round(mean(gs, function(g) { return g.lo[k]; })), Math.round(mean(gs, function(g) { return g.hi[k]; })), Math.round(mean(gs, function(g) { return g.fin ? g.fin[k] || 0 : 0; })),
    startsLow ? '(starts at 0)' : pct(gs.filter(function(g) { return g.lo[k] <= 5; }).length, gs.length) + '%', pct(gs.filter(function(g) { return g.hi[k] >= 95; }).length, gs.length) + '%']));
});
var withMem = games.filter(function(g) { return g.hi && g.hi.members !== undefined && g.fin; });
L.push('', 'Members (thousands): mean low ' + Math.round(mean(withMem, function(g) { return g.lo.members; })) + ', mean high ' + Math.round(mean(withMem, function(g) { return g.hi.members; })) +
  ', mean at the end ' + Math.round(mean(withMem, function(g) { return g.fin.members; })) + '; ' + pct(withMem.filter(function(g) { return g.hi.members >= (g.fin.mem_cap || 400) - 0.5; }).length, withMem.length) + '% of games hit the party\'s membership limit. ' +
  'Legal status at the end: ' + fmt(tally(withMem, function(g) { return ['banned', 'persecuted', 'harassed', 'legal'][Math.max(0, Math.min(3, Math.round(g.fin.legality)))]; }), withMem.length) + ' (%).');
// does the ruble come back?
var rubleLow = games.filter(function(g) { return g.lo && g.lo.ruble <= 10 && g.fin; });
L.push('', 'The ruble: of the ' + rubleLow.length + ' games where it fell to 10 or less, it ended above 25 in ' + pct(rubleLow.filter(function(g) { return g.fin.ruble > 25; }).length, rubleLow.length) +
  '% and above 40 in ' + pct(rubleLow.filter(function(g) { return g.fin.ruble > 40; }).length, rubleLow.length) + '%. Bread: of the ' + games.filter(function(g) { return g.lo && g.lo.bread <= 10; }).length +
  ' games where it fell to 10 or less, it ended above 25 in ' + pct(games.filter(function(g) { return g.lo && g.lo.bread <= 10 && g.fin && g.fin.bread > 25; }).length, games.filter(function(g) { return g.lo && g.lo.bread <= 10; }).length) + '%.');
L.push('', 'Turns spent with no resources (0): ' + Math.round(100 * mean(games, function(g) { return g.turns ? g.zeroRes / g.turns : 0; })) + '% on average; ' +
  pct(games.filter(function(g) { return g.turns && g.zeroRes / g.turns > 0.3; }).length, games.length) + '% of games spend over 30% of their turns broke.', '');

// content coverage
var scenesDir = path.join(ROOT, 'source', 'scenes');
var events = fs.readdirSync(path.join(scenesDir, 'events')).filter(function(f) { return /\.scene\.dry$/.test(f); }).map(function(f) { return f.replace('.scene.dry', ''); });
var cardDirs = ['party_affairs', 'coalition_affairs', 'soviet_affairs'], cards = [];
cardDirs.forEach(function(d) { try { fs.readdirSync(path.join(scenesDir, d)).forEach(function(f) { if (/\.scene\.dry$/.test(f)) { cards.push(f.replace('.scene.dry', '')); } }); } catch (e) { /* none */ } });
function coverage(ids, title) {
  var seen = {};
  ids.forEach(function(id) { seen[id] = {}; });
  games.forEach(function(g) { (g.seen || []).forEach(function(id) { if (seen[id]) { seen[id][g.config.party] = (seen[id][g.config.party] || 0) + 1; } }); });
  var nParty = tally(games, function(g) { return g.config.party; });
  var never = ids.filter(function(id) { return !Object.keys(seen[id]).length; });
  var rare = ids.filter(function(id) { var t = 0; for (var p in seen[id]) { t += seen[id][p]; } return t && t < games.length * 0.02; });
  L.push('## ' + title, '', 'Seen in at least one game: ' + (ids.length - never.length) + ' of ' + ids.length + '.', '');
  L.push('- Never seen: ' + (never.length ? never.map(function(x) { return '`' + x + '`'; }).join(', ') : 'none'));
  L.push('- Rare (under 2% of games): ' + (rare.length ? rare.map(function(x) { var t = 0; for (var p in seen[x]) { t += seen[x][p]; } return '`' + x + '` (' + t + ')'; }).join(', ') : 'none'), '');
  return {seen: seen, nParty: nParty};
}
coverage(events, 'Events reached');
coverage(cards, 'Cards drawn');

// cards played
var plays = {};
games.forEach(function(g) { for (var id in g.played || {}) { plays[id] = (plays[id] || 0) + g.played[id]; } });
var totalPlays = Object.keys(plays).reduce(function(a, k) { return a + plays[k]; }, 0);
L.push('## Most played cards and actions', '', Object.keys(plays).sort(function(a, b) { return plays[b] - plays[a]; }).slice(0, 25)
  .map(function(k) { return '`' + k + '` ' + (100 * plays[k] / totalPlays).toFixed(1) + '%'; }).join(', '), '');

fs.mkdirSync(path.join(ROOT, 'docs'), {recursive: true});
fs.writeFileSync(path.join(ROOT, 'docs', 'fuzz_report.md'), L.join('\n') + '\n');
var raw = process.env.RAW || path.join(os.tmpdir(), 'ro_fuzz_' + SEED0 + '.json');
fs.writeFileSync(raw, JSON.stringify({seed: SEED0, games: games, failures: failures, crashes: crashes}));
console.log('wrote docs/fuzz_report.md and ' + raw);
